version: "3.9"

services:
  wrf:
    build:
      context: .
      dockerfile: WRF/Dockerfile
    container_name: 'uniman-emep-wrf'
  emep:
    build:
      context: .
      dockerfile: EMEP/Dockerfile
    container_name: 'uniman-emep'

